---
- name: Set some facts for AAP {{ casc_aap_version }}
  ansible.builtin.set_fact:
    controller_hostname: "{{ aap_hostname }}"
    controller_host: "{{ aap_hostname }}"
    controller_validate_certs: "{{ aap_validate_certs }}"
    controller_oauthtoken: "{{ controller_token.token | default(vault_aap_token) }}"
    controller_configuration_async_retries: "{{ aap_configuration_async_retries | default(omit) }}"
    controller_configuration_async_delay: "{{ aap_configuration_async_delay | default(omit) }}"
    controller_configuration_secure_logging: "{{ aap_configuration_secure_logging | default(omit) }}"
  tags:
    - always

- name: Include Import Tasks for AAP {{ casc_aap_version }}
  vars:
    __import_type: "{{ 'flat' if flatten_output | default(false) | bool else 'filetree' }}"
  ansible.builtin.include_tasks: "import_{{ __import_type }}.yml"
  tags:
    - always

- name: Dispatch for AAP {{ casc_aap_version }}
  ansible.builtin.import_role:
    name: infra.controller_configuration.dispatch
...
